refactor: clean up add-rn-version scripts

diff --git a/scripts/add-rn-version b/scripts/add-rn-version
--- a/scripts/add-rn-version
+++ b/scripts/add-rn-version
@@ -2,6 +2,7 @@
 # Script to generate React-Native native code for a specific version template.
 
 CMDNAME=$(basename "$0")
+ORIG_DIR=$(pwd)
 TEMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t 'rn-template')
 TEMPLATE_REL_DIR="./packages/templates/react-native"
 TEMPLATE_DIR=$(realpath "$TEMPLATE_REL_DIR")
@@ -76,5 +77,12 @@ rm -rf "$TEMP_DIR"
 echo "React-Native version template for $RN_VERSION generated successfully at $NEW_TEMPLATE_DIR"
 echo ""
 echo "Updating CLI tools to recognize the new version ..."
+
+## Echo CWD
+if ! cd "$ORIG_DIR"
+then
+  echo "Failed to change directory back to $ORIG_DIR"
+  exit 1
+fi
 
 npx tsx ./scripts/add-rn-version-codemods.ts "$RN_VERSION"
