chore(workspace): formatting error message
brandingbrand-source-id: 1c2deb8998bff05bdc4305b657e88b1421966f44

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -15,12 +15,12 @@ IS_AMEND=$(ps -wwo ppid=$PPID,command | grep 'git commit' | head -1 | grep -c -e
 set -e
 
 if [ "$IS_AMEND" -gt 0 ]; then
-  ./node_modules/.bin/nx format:check --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
+  ./node_modules/.bin/nx format:check --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached) || (echo "The files above have formatting errors. Please run \`nx format\` to correct these." && exit 1)
   ./node_modules/.bin/nx affected:test --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
   ./node_modules/.bin/nx affected:lint --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
 else
   ./tools/verify-commit.ts $1
-  ./node_modules/.bin/nx format:check --files $(git diff --name-only --cached)
+  ./node_modules/.bin/nx format:check --files $(git diff --name-only --cached) || (echo "The files above have formatting errors. Please run \`nx format\` to correct these." && exit 1)
   ./node_modules/.bin/nx affected:test --files $(git diff --name-only --cached)
   ./node_modules/.bin/nx affected:lint --files $(git diff --name-only --cached)
 fi
