perf(workspace): be smarter about concurrency levels in test & lint
brandingbrand-source-id: 98844e0656647d89e4b737bc111031caf8acefe4

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,6 +1,12 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+if [ -f "$HOME/.brandingbrandrc" ]; then
+  echo "Reading configuration from $HOME/.brandingbrandrc";
+  . "$HOME/.brandingbrandrc";
+fi
+
+
 if [ -t 1 ]; then
   exec </dev/tty
 fi
@@ -8,19 +14,23 @@ fi
 ./node_modules/.bin/commitlint -e $1
 ./node_modules/.bin/nx workspace-lint
 
-# Checking for --ammend will fail when not amending
+# Checking for --amend will fail when not amending
 # This is not a reason to exit the program
 set +e
 IS_AMEND=$(ps -wwo ppid=$PPID,command | grep 'git commit' | head -1 | grep -c -e '--amend')
 set -e
 
+
+PARALLEL=$(expr $(sysctl -n hw.logicalcpu 2>/dev/null || nproc 2>/dev/null || echo "5" ) - 2);
+PARALLEL="${NX_PARALLEL:-$PARALLEL}"
+
 if [ "$IS_AMEND" -gt 0 ]; then
   ./node_modules/.bin/nx format:check --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached) || (echo "The files above have formatting errors. Please run \`nx format\` to correct these." && exit 1)
-  ./node_modules/.bin/nx affected:test --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
-  ./node_modules/.bin/nx affected:lint --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
+  ./node_modules/.bin/nx affected:test --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached) --parallel "${PARALLEL}"
+  ./node_modules/.bin/nx affected:lint --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached) --parallel "${PARALLEL}"
 else
   ./tools/verify-commit.ts $1
   ./node_modules/.bin/nx format:check --files $(git diff --name-only --cached) || (echo "The files above have formatting errors. Please run \`nx format\` to correct these." && exit 1)
-  ./node_modules/.bin/nx affected:test --files $(git diff --name-only --cached)
-  ./node_modules/.bin/nx affected:lint --files $(git diff --name-only --cached)
+  ./node_modules/.bin/nx affected:test --files $(git diff --name-only --cached) --parallel "${PARALLEL}"
+  ./node_modules/.bin/nx affected:lint --files $(git diff --name-only --cached) --parallel "${PARALLEL}"
 fi
