chore(workspace): handle commits on linux
brandingbrand-source-id: 1df35af80217b383ce6050acafe2ad83a9801479

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -8,8 +8,13 @@ fi
 ./node_modules/.bin/commitlint -e $1
 ./node_modules/.bin/nx workspace-lint
 
-IS_AMEND=$(ps -wwo ppid=$PPID,command | grep 'git commit' | head -1 | grep -c -e '--amend' || [[ $? == 1 ]])
-if [ -n "$IS_AMEND" ]; then
+# Checking for --ammend will fail when not amending
+# This is not a reason to exit the program
+set +e
+IS_AMEND=$(ps -wwo ppid=$PPID,command | grep 'git commit' | head -1 | grep -c -e '--amend')
+set -e
+
+if [ "$IS_AMEND" -gt 0 ]; then
   ./node_modules/.bin/nx format:check --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
   ./node_modules/.bin/nx affected:test --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
   ./node_modules/.bin/nx affected:lint --files $(git diff-tree --no-commit-id --name-only -r HEAD) $(git diff --name-only --cached)
